# Generated by Django 3.2.19 on 2023-08-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_auto_20230730_1306'),
        ('checkout', '0005_alter_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.IntegerField(default=0),
        ),
    ]
