# Generated by Django 3.2.19 on 2023-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='Standard', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_time_min', models.PositiveIntegerField(default=10)),
                ('delivery_time_max', models.PositiveIntegerField(default=21)),
                ('processing_time', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
