# Generated by Django 3.2.19 on 2023-07-30 10:38

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20230730_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='delivery_time',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=[10, 21]),
        ),
    ]
