# Generated by Django 3.2.19 on 2023-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shipping_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='method',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
