# Generated by Django 3.2.19 on 2023-07-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_shipping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivery_time_max',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivery_time_min',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='processing_time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
